# Generated by Django 4.2.4 on 2023-10-31 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FirstLibreria.author')),
                ('genre_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FirstLibreria.genre')),
                ('publisher_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FirstLibreria.publisher')),
            ],
        ),
    ]
